/* eslint-disable */
export const memory: WebAssembly.Memory;
export function solutiondomain_new(a: number, b: number): number;
export function __wbg_hardcstr_free(a: number): void;
export function hardcstr_new(a: number): number;
export function obj_new(a: number, b: number): number;
export function __wbg_optfacade_free(a: number): void;
export function optfacade_solve(a: number, b: number): number;
export function __wbg_optfacadebuilder_free(a: number): void;
export function optfacadebuilder_new(): number;
export function optfacadebuilder_build(a: number, b: number): number;
export function optfacadebuilder_max_iterations(a: number, b: number): number;
export function optfacadebuilder_objs_goals(a: number, b: number, c: number): number;
export function optfacadebuilder_stagnation_percentage(a: number, b: number): number;
export function optfacadebuilder_stagnation_threshold(a: number, b: number): number;
export function __wbg_optproblem_free(a: number): void;
export function optproblem_with_capacity(a: number, b: number): number;
export function optproblem_definitions(a: number): number;
export function optproblem_results(a: number): number;
export function __wbg_optproblemdefinitions_free(a: number): void;
export function __wbg_optproblemdefinitionsbuilder_free(a: number): void;
export function optproblemdefinitionsbuilder_new(): number;
export function optproblemdefinitionsbuilder_build(a: number): number;
export function optproblemdefinitionsbuilder_domain(a: number, b: number): number;
export function optproblemdefinitionsbuilder_name(a: number, b: number, c: number): number;
export function optproblemdefinitionsbuilder_push_hard_cstr(a: number, b: number): number;
export function optproblemdefinitionsbuilder_push_obj(a: number, b: number): number;
export function __wbg_optproblemresults_free(a: number): void;
export function optproblemresults_best(a: number): number;
export function optproblemresults_get(a: number, b: number): number;
export function optproblemresults_len(a: number): number;
export function __wbg_optproblemresult_free(a: number): void;
export function optproblemresult_hard_cstrs(a: number, b: number): void;
export function optproblemresult_objs(a: number, b: number): void;
export function optproblemresult_objs_avg(a: number): number;
export function optproblemresult_solution(a: number): number;
export function __wbg_pct_free(a: number): void;
export function pct_from_decimal(a: number): number;
export function pct_from_percent(a: number): number;
export function solution_array(a: number, b: number): void;
export function __wbg_solutiondomain_free(a: number): void;
export function __wbg_solution_free(a: number): void;
export function __wbg_obj_free(a: number): void;
export function __wbindgen_malloc(a: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number): number;
export function __wbindgen_free(a: number, b: number): void;
export function __wbindgen_exn_store(a: number): void;
