name: CI
on: push

jobs:
  build_and_release:
    name: Build and release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
      - run: yarn install
      - run: yarn build

      - env:
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          cd dist
          git init
          git config user.name "GitHub Actions"
          git config user.email "github-actions-bot@users.noreply.github.com"
          git add .
          git commit -m "Build $(date "+%Y-%m-%d")"
          REMOTE=https://$TOKEN@github.com/c410-f3r/mop-playground.git
          git push --force $REMOTE master:master
